config/routes.rb
FishSite::Application.routes.draw do
  resources :notes

  resources :weathers

  get "fish/user_photo"
  post 'upload', to: 'fish#upload'

  devise_for :users
  resources :fish

	root to: 'fish#index'

end

app/models/weather.rb
class Weather < ActiveRecord::Base
	belongs_to :fish
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  before_action :set_weather, only: [:show, :edit, :update, :destroy]

  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
  end

  # GET /weathers/new
  def new
    @weather = Weather.new
  end

  # GET /weathers/1/edit
  def edit
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(weather_params)

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weather }
      else
        format.html { render action: 'new' }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weathers/1
  # PATCH/PUT /weathers/1.json
  def update
    respond_to do |format|
      if @weather.update(weather_params)
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather.destroy
    respond_to do |format|
      format.html { redirect_to weathers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weather
      @weather = Weather.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weather_params
      params.require(:weather).permit(:weather_info, :fish_id, :currentTime, :moonPercentage, :location, :zipCode, :elevation, :observationLocation, :observationLocationElevation, :observationTime, :currentWeather, :temperature, :relative_humidity, :windInformation, :precipToday)
    end
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/weathers/_form.html.erb
<%= form_for(@weather) do |f| %>
  <% if @weather.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weather.errors.count, "error") %> prohibited this weather from being saved:</h2>

      <ul>
      <% @weather.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :weather_info %><br>
    <%= f.text_field :weather_info %>
  </div>
  <div class="field">
    <%= f.label :fish_id %><br>
    <%= f.number_field :fish_id %>
  </div>
  <div class="field">
    <%= f.label :currentTime %><br>
    <%= f.text_field :currentTime %>
  </div>
  <div class="field">
    <%= f.label :moonPercentage %><br>
    <%= f.text_field :moonPercentage %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :zipCode %><br>
    <%= f.text_field :zipCode %>
  </div>
  <div class="field">
    <%= f.label :elevation %><br>
    <%= f.text_field :elevation %>
  </div>
  <div class="field">
    <%= f.label :observationLocation %><br>
    <%= f.text_field :observationLocation %>
  </div>
  <div class="field">
    <%= f.label :observationLocationElevation %><br>
    <%= f.text_field :observationLocationElevation %>
  </div>
  <div class="field">
    <%= f.label :observationTime %><br>
    <%= f.text_field :observationTime %>
  </div>
  <div class="field">
    <%= f.label :currentWeather %><br>
    <%= f.text_field :currentWeather %>
  </div>
  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :relative_humidity %><br>
    <%= f.text_field :relative_humidity %>
  </div>
  <div class="field">
    <%= f.label :windInformation %><br>
    <%= f.text_field :windInformation %>
  </div>
  <div class="field">
    <%= f.label :precipToday %><br>
    <%= f.text_field :precipToday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weathers/edit.html.erb
<h1>Editing weather</h1>

<%= render 'form' %>

<%= link_to 'Show', @weather %> |
<%= link_to 'Back', weathers_path %>

app/views/weathers/index.html.erb
<h1>Listing weathers</h1>

<table>
  <thead>
    <tr>
      <th>Weather info</th>
      <th>Fish</th>
      <th>Currenttime</th>
      <th>Moonpercentage</th>
      <th>Location</th>
      <th>Zipcode</th>
      <th>Elevation</th>
      <th>Observationlocation</th>
      <th>Observationlocationelevation</th>
      <th>Observationtime</th>
      <th>Currentweather</th>
      <th>Temperature</th>
      <th>Relative humidity</th>
      <th>Windinformation</th>
      <th>Preciptoday</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @weathers.each do |weather| %>
      <tr>
        <td><%= weather.weather_info %></td>
        <td><%= weather.fish_id %></td>
        <td><%= weather.currentTime %></td>
        <td><%= weather.moonPercentage %></td>
        <td><%= weather.location %></td>
        <td><%= weather.zipCode %></td>
        <td><%= weather.elevation %></td>
        <td><%= weather.observationLocation %></td>
        <td><%= weather.observationLocationElevation %></td>
        <td><%= weather.observationTime %></td>
        <td><%= weather.currentWeather %></td>
        <td><%= weather.temperature %></td>
        <td><%= weather.relative_humidity %></td>
        <td><%= weather.windInformation %></td>
        <td><%= weather.precipToday %></td>
        <td><%= link_to 'Show', weather %></td>
        <td><%= link_to 'Edit', edit_weather_path(weather) %></td>
        <td><%= link_to 'Destroy', weather, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weather', new_weather_path %>

app/views/weathers/new.html.erb
<h1>New weather</h1>

<%= render 'form' %>

<%= link_to 'Back', weathers_path %>

app/views/weathers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weather info:</strong>
  <%= @weather.weather_info %>
</p>

<p>
  <strong>Fish:</strong>
  <%= @weather.fish_id %>
</p>

<p>
  <strong>Currenttime:</strong>
  <%= @weather.currentTime %>
</p>

<p>
  <strong>Moonpercentage:</strong>
  <%= @weather.moonPercentage %>
</p>

<p>
  <strong>Location:</strong>
  <%= @weather.location %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @weather.zipCode %>
</p>

<p>
  <strong>Elevation:</strong>
  <%= @weather.elevation %>
</p>

<p>
  <strong>Observationlocation:</strong>
  <%= @weather.observationLocation %>
</p>

<p>
  <strong>Observationlocationelevation:</strong>
  <%= @weather.observationLocationElevation %>
</p>

<p>
  <strong>Observationtime:</strong>
  <%= @weather.observationTime %>
</p>

<p>
  <strong>Currentweather:</strong>
  <%= @weather.currentWeather %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @weather.temperature %>
</p>

<p>
  <strong>Relative humidity:</strong>
  <%= @weather.relative_humidity %>
</p>

<p>
  <strong>Windinformation:</strong>
  <%= @weather.windInformation %>
</p>

<p>
  <strong>Preciptoday:</strong>
  <%= @weather.precipToday %>
</p>

<%= link_to 'Edit', edit_weather_path(@weather) %> |
<%= link_to 'Back', weathers_path %>