config/routes.rb
FishSite::Application.routes.draw do
  resources :notes

  resources :weathers

  get "fish/user_photo"
  post 'upload', to: 'fish#upload'

  devise_for :users
  resources :fish

	root to: 'fish#index'

end

app/models/fish.rb
class Fish < ActiveRecord::Base
	belongs_to :user
	has_many :weathers, dependent: :destroy
	has_many :notes, dependent: :destroy
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
	skip_before_filter  :verify_authenticity_token
  before_action :set_fish, only: [:show, :edit, :update, :destroy]
  # GET /fish
  # GET /fish.json
  def index
		@user = User.find(current_user)
		if Fish.exists?(current_user.id)
			@fish = @user.fish
		else
		puts "nothing"
		end
		@hash = Gmaps4rails.build_markers(@fish) do |fish, marker|
  	marker.lat fish.latitude
  	marker.lng fish.longitude
		marker.infowindow "Fish #{fish.id}\nType Caught #{fish.fish_type}\nLength #{fish.fish_length}\nWeight #{fish.fish_weight}\nCaught on #{fish.caught_on}"
		end
  end
	def image_convert(fish_id)
		puts "jhsahjghsgadsgh"
		puts fish_id
		if params[:fish][:fish_photo]
			pixels = hex_to_string(params[:fish][:fish_photo])
			data = StringIO.new(pixels)
			data.class.class_eval { attr_accessor :original_filename, :content_type }
    	data.original_filename = "fish#{fish_id}.jpeg"
    	data.content_type = "image/jpeg"
				
  		File.open(Rails.root.join('public', 'assets', data.original_filename), 'wb') do |file|
    		file.write(data.read)
			end
		end
	end
	#converts the data from hex to a string -> found code here http://4thmouse.com/index.php/2008/02/18/converting-hex-to-binary-in-4-languages/
  def hex_to_string(hex)
 	temp = hex.gsub("\s", "");
    ret = []
    (0...temp.size()/2).each{|index| ret[index] = [temp[index*2, 2]].pack("H2")}
    file = String.new
    ret.each { |x| file << x}
    file  
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
		puts "pic" *10
		puts @fish.fish_photo
		@note = Note.new
		@note.fish_id = @fish.id
		@weathers = @fish.weathers
		@notes = @fish.notes
		@fishWeather =  @weathers[0]
		@notes.each do |n|
		puts n
		end
  end

	def upload
		file = params[:Photo]
		@user = User.find(current_user.id)
		@user.first_name = params[:first_name]
		@user.last_name =params[:last_name]
		@user.photo = file.original_filename
		uploaded_io = file
  	File.open(Rails.root.join('public', 'assets', uploaded_io.original_filename), 'wb') do |file|
    	file.write(uploaded_io.read)
  	end
		if @user.save
    	respond_to do |format|
      	if @user.save
        	format.html { redirect_to root_url, notice: 'Photo was uploaded successfully' }
      	else
        	format.html { render action: 'fish' }
        	format.json { render json: @user.errors, status: :unprocessable_entity }
     	 	end
    	end
		end

	end
	def user_photo
		@user = User.find(current_user)
	end

  # GET /fish/new
  def new
    @fish = Fish.new
  end

  # GET /fish/1/edit
  def edit
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(fish_params)
		@user = User.find_by email: params[:user][:email]
		@fish.user_id = @user.id
		if @fish.save
			@fish.fish_photo = "fish#{@fish.id}.jpeg"
			@fish.save
			image_convert(@fish.id)
    	@weather = @fish.weathers.create(weather_params)
    	respond_to do |format|
      	if @weather.save
        	format.html { redirect_to @fish, notice: 'Fish was successfully created.' }
        	format.json { render action: 'show', status: :created, location: @fish }
      	else
        	format.html { render action: 'new' }
        	format.json { render json: @fish.errors, status: :unprocessable_entity }
      	end
    	end
		end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fish_params
      params.require(:fish).permit(:user_id, :fish_type, :fish_length, :fish_weight, :caught_on, :longitude, :latitude, :caught_date, :fish_photo)
    end
		def weather_params
			params.require(:weather).permit(:weather_info, :currentTime, :moonPercentage,  :location,  :zipCode, :elevation, :observationLocation, :observationLocationElevation, :observationTime, :currentWeather, :temperature, :relative_humidity, :windInformation, :precipToday)
		end

end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= form_for(@fish) do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fish_type %><br>
    <%= f.text_field :fish_type %>
  </div>
  <div class="field">
    <%= f.label :fish_length %><br>
    <%= f.text_field :fish_length %>
  </div>
  <div class="field">
    <%= f.label :fish_weight %><br>
    <%= f.text_field :fish_weight %>
  </div>
  <div class="field">
    <%= f.label :caught_on %><br>
    <%= f.text_field :caught_on %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Editing fish</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<!-- Header and Nav -->
	<div class="row"> 
    <div class="large-12 columns">
      <div class="panel">
        <h1>Daniel's Fish Dashboard</h1>
      </div>
    </div>
	</div>
  <!-- End Header and Nav -->
  <div class="row">
 <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="large-3 columns ">
      <div class="panel">
				<% if !@user.photo.nil? %>
        	<a href="/fish/user_photo"><%=image_tag("/assets/#{@user.photo}", :alt => "profile")%></a>
        <% else %>
        	<a href="/fish/user_photo"><img src="http://www.clubwebsite.co.uk/img/misc/noImageAvailable.jpg" alt="null image"></a>
        <% end %>
        		<h5><a href="#"><%=@user.first_name%> <%=@user.last_name%></a></h5>
          <div class="section-container vertical-nav" data-section data-options="deep_linking: false; one_up: true">
          <section class="section">
						<button id="show">Fish List</button>
						<div style="display: none" id="fish">
						<% if !@fish.nil? %>
						<%@fish.each do |fish| %>
						<p><%= link_to "fish #{fish.id}",fish_path(fish.id) %></p>
						<% end %>
						<% end %>	
						<button id="hidefish">Hide List</button>
						</div>
          </section>
        </div>
 
      </div>
    </div>
    
    <!-- Main Feed -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-6 columns">
 
      <!-- Feed Entry -->
      <div class="row">
        <div class="large-2 columns small-3">
					<div style='width: 800px;'>
  					<div id="map" style='width: 800px; height: 400px;'></div>
					</div>
					<script type="text/javascript">
						handler = Gmaps.build('Google');
						handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
						markers = handler.addMarkers(<%=raw @hash.to_json %>);
  					handler.bounds.extendWith(markers);
  					handler.fitMapToBounds();
						});
					</script>
				</div>
        <div class="large-10 columns">

        </div>
      </div>
		</div>
 
  <!-- Footer -->
 
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-5 columns">
          <p>&copy; Built By Daniel Fucking Roach.</p>
        </div>
        <div class="large-7 columns">
          <ul class="inline-list right">
            <li><a href="#">Google Maps</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/fish/new.html.erb
<h1>New fish</h1>

<%= render 'form' %>

<%= link_to 'Back', fish_index_path %>

app/views/fish/show.html.erb
<body>
<!-- Header and Nav -->
    <div class="large-12 columns">
      <div class="panel">
        <h1>Daniel's Fish</h1>
      </div>
    </div>
 <!-- Main Page Content and Sidebar -->
 
  <div class="row">
 
    <!-- Main Blog Content -->
      <hr />
 
      <article>
 
        <h2><a href="#">Fish <%= @fish.id %></a></h2>
        <h3>Fish Information</h3>
 
        <div class="row">
          <div class="large-6 columns">
						<ul class="circle">
  						<li><h5>Type of Fish Caught: <%= @fish.fish_type %></h5></li>
  						<li><b>Length Of Fish: <%= @fish.fish_length %> inches</b></li>
  						<li><b>Weight Of Fish: <%= @fish.fish_weight %> lbs</b></li>
  						<li><b>Fish Was Caught On: <%= @fish.caught_on %></b></li>
						</ul>
							<div>
  							<h4 class="panel callout radius"><a><li id="weatherData">Weather Data</li></a></h4>
    						<ul class="circle">
									<div style="display: none" id="weatherPanel">
      						<li><strong>Current Time: <%= @fishWeather.currentTime  %></strong> </li>
     						 	<li><strong>Moon percentage: <%= @fishWeather.moonPercentage %></strong></li>
      						<li><strong>Location Of Catch: <%= @fishWeather.location %></strong></li>
									<li><strong>Zip Code: <%= @fishWeather.zipCode %></strong></li>
									<li><strong>Elevation: <%= @fishWeather.elevation %></strong></li>
									<li><strong>Observation Location: <%= @fishWeather.observationLocation %></strong></li>
									<li><strong>Observation Location Elevation: <%= @fishWeather.observationLocationElevation %></strong></li>
									<li><strong>Observation Time: <%= @fishWeather.observationTime %></strong></li>
									<li><strong>Current Weather: <%= @fishWeather.currentWeather %></strong></li>
									<li><strong>Temperature: <%= @fishWeather.temperature %></strong></li>
									<li><strong>Relative Humidity: <%= @fishWeather.relative_humidity %></strong></li>
									<li><strong>Wind Information: <%= @fishWeather.windInformation %></strong></li>
									<li><strong>Precipitation That Day: <%= @fishWeather.precipToday %></strong></li>
									</div>
    						</ul>
						</div>
          </div>
          <div class="large-6 columns">
						<%=image_tag("/assets/#{@fish.fish_photo}", :alt => "Fish Caught")%>
          </div>
        </div>
 
      </article>

 
    </div>
 
    <!-- End Main Content -->
    <!-- comments start here -->
	<div class="row">
		<hr />
 		<h3><div class="panel callout radius"><li id="commentsTab">Comments And Notes</li></h3>
					<div>
					
					</div>
      			<div class="row">
							<div>
								<ul>
									<%= @notes.each do |note| %>
										<% if !note.comment.nil? %>
										<li>Comment: <%= note.comment %> </li>
										<% end %>
										<% if !note.note.nil? %>
										<li>Note: <%= note.note %> </li>
										<% end %>
									<% end %>
								</ul>
							</div>
        			<div class="small-3 columns">
								<%= form_for(@note) do |f| %>
  								<div class="field">
    								<%= f.label :comment %><br>
    								<%= f.text_field :comment %>
  								</div>
  								<div class="field">
    								<%= f.label :note %><br>
    								<%= f.text_area :note %>
  								</div>
    								<%= f.hidden_field :fish_id %>
  								<div class="actions">
    								<%= f.submit %>
  								</div>
								<% end %>
							</div>
						</div>
					</div>
	</div>
 
  <!-- End Main Content and Sidebar -->
 </body>
  <!-- Footer -->
 
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>© Built By Daniel Roach</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
						<li><%= link_to 'Back To Dashboard', root_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/fish/user_photo.html.erb
<div class="row">
<!-- Header and Nav -->
    <div class="large-12 columns">
      <div class="panel">
        <h1>Profile</h1>
      </div>
    </div>
 <!-- Main Page Content and Sidebar -->
	<div class="large-12 columns"> 
    	<!-- Thumbnails -->
				<div class="large-3 small-6 columns">
					<% if @user.photo.nil? %>
						<div>
   	 					<img src="http://placehold.it/250x250&text=Thumbnail" />
    	 				<h6 class="panel">Description</h6>
						</div>
					<% else %>
						<div>
        			<img src="/assets/<%=@user.photo %>"/>
    	 				<h6 class="panel"><%= @user.email %></h6>
						</div>
					<% end %>
					<%= form_tag({action: :upload}, multipart: true) do %>
					<div>
						<%= label_tag(:first_name, "First Name:") %>
  					<%= text_field_tag(:first_name) %>
					</div>
					<div>
						<%= label_tag(:last_name, "First Name:") %>
  					<%= text_field_tag(:last_name) %>
					</div>
					<div>
						<%= file_field_tag 'Photo' %>
 					</div>
					<div>
 						<%= submit_tag("upload") %>
					</div>
					<% end %>
		<%= link_to 'Back To Dashboard', root_path %>
				</div>
	</div>
</div>